version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn
      - run: node --version
      - run: truffle version
      - run: npm run test
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  docs:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn
      - run: node --version
      - run: truffle version
      - run: npm run docs
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
workflows:
  version: 2
  test_and_docs:
    jobs:
      - test
      - docs
      