version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn install
      - run: sudo npm i truffle -g
      - run: node --version
      - run: truffle version
      - run: truffle compile
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:8
    parallelism: 3
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn install
      - run: sudo npm i truffle -g
      - run: node --version
      - run: truffle version
      - run: npm run test
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: ./test-results/mocha/results.xml
  coverage:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn install
      - run: sudo npm i truffle -g
      - run: node --version
      - run: truffle version
      - run: npm run coverage
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - store_artifacts:
          path: ./coverage/lcov.info
  docs:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn install
      - run: sudo npm i truffle -g
      - run: node --version
      - run: truffle version
      - run: npm run docs
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
workflows:
  version: 2
  commit:
    jobs:
      - test
      - coverage:
          type: approval
  daily-builds:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
                - development-2.1.0
                - development-3.0.0
    jobs:
      - test
      - coverage
  docs:
    jobs:
      - docs:
          filters:
            branches:
              only:
                - master